#!/bin/sh

# Monitor setup.

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x /usr/local/bin/dual_monitor_setup ];then
    dual_monitor_setup
fi

# bspc monitor eDP-1-1 -d 1 2 3 4 5
# bspc monitor HDMI-1 -d 6 7 8 9 0

monitors=$(xrandr -q | grep " connected " | awk '{ print$1 }')
monitors=($monitors)

if [[ ${#monitors[@]} == 1 ]]; then
    bspc monitor ${monitors[0]} -d 1 2 3 4 5 6 7 8 9 10
else
    bspc monitor ${monitors[1]} -d 1 2 3 4 5
    bspc monitor ${monitors[0]} -d 6 7 8 9 10
fi

# Launch applications.
$HOME/.config/bspwm/autostart.sh

# BSPWM configuration.
bspc config border_width            2
bspc config window_gap              6

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true

bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true

# BSPWM coloring.
bspc config normal_border_color     "#4c566a"
bspc config active_border_color     "#1e1e1e"
bspc config focused_border_color    "#5e81ac"
bspc config presel_feedback_color   "#5e81ac"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunderbird desktop='^2'
bspc rule -a Slack desktop='^3'

# Alter compton settings if using intel graphics
GRAPHIC_CARD=$(lspci | grep -i "vga" | sed 's/.*://' | sed 's/(.*//' | sed 's/^[ \t]*//')
if [[ $(echo $GRAPHIC_CARD | grep -i 'intel\|lenovo') != "" ]]; then MCODE='initrd=\intel-ucode.img'
  sed -i 's/"xrender"/"glx"/' ~/.config/compton.conf
  grep -q 'vsync = "opengl-swc";' ~/.config/compton.conf || echo 'vsync = "opengl-swc";' >> ~/.config/compton.conf
fi

