#! /bin/sh

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x /usr/local/bin/dual_monitor_setup ];then
    dual_monitor_setup
fi

bspc monitor eDP-1-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 0

# Launch applications.
$HOME/.config/bspwm/autostart.sh

# BSPWM configuration.
bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true

bspc config pointer_modifier     mod4
bspc config pointer_action1      move
bspc config pointer_action2      resize_side
bspc config pointer_action3      resize_corner

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

