shell fish

font_family       FiraCode Nerd Font Mono
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         14.0

background_opacity  0.95
background_blur     20

window_padding_width  18 24

hide_window_decorations   titlebar-only

# Setup layouts
enabled_layouts horizontal, vertical, tall:bias=50;full_size=1;mirrored=false, fat:bias=50;full_size=1;mirrored=false

# Move the active window in the indicated direction
map ctrl+shift+up move_window up
map ctrl+shift+left move_window left
map ctrl+shift+right move_window right
map ctrl+shift+down move_window down

# Switch focus to the neighboring window in the indicated direction
map shift+left neighboring_window left
map shift+right neighboring_window right
map shift+up neighboring_window up
map shift+down neighboring_window down

# OS-specific tweaks.
macos_quit_when_last_window_closed yes
macos_show_window_title_in none

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
